export const RATE_LIMIT_WINDOW_MINUTES = 15;
export const RATE_LIMIT_WINDOW_MS = RATE_LIMIT_WINDOW_MINUTES * 60 * 1000; // 15 minutes
export const RATE_LIMIT_MAX_REQUESTS = 5; // Limit each IP to 5 requests per windowMs
export const RESEND_RATE_LIMIT_MAX_REQUESTS = 3; // Limit resend requests to 3 per 15 minutes per IP
export const REFRESH_RATE_LIMIT_MAX = 60; // per IP per window (RATE_LIMIT_WINDOW_MS)
export const REGISTER_RATE_LIMIT_MAX = 10; // registrations per IP per window
export const LOGIN_MAX_FAILURES = 5; // failed logins per email+IP before a lockout starts
export const LOGIN_LOCKOUT_BASE_SECONDS = 60; // first lockout; doubles with each further failure
export const LOGIN_LOCKOUT_MAX_SECONDS = 15 * 60; // lockout never exceeds one rate-limit window
export const LOGIN_FAILURE_WINDOW_SECONDS = 60 * 60; // failure counter expires after quiet hour
